### ISSUE TITLE
cannot sort array of C-style string using std::sort

### ISSUE THREAD

**Issue by chAngeZhaoZhanBo** [LC-John/HWSolutions2Introduction2Computation#2]
https://github.com/LC-John/HWSolutions2Introduction2Computation/blame/midterm/2020%E5%B9%B4%E6%9C%9F%E4%B8%AD%E8%80%83%E8%AF%95/README.md#L287 中提到使用sort with strcmp排序字符串，但std::sort无法对array of C-style string进行排序（std::sort要求被排序元素是assignable，而char [N]不是assignable的）

要么使用std::string来表示字符串，要么使用直接操作内存的qsort

**Comment by LC-John** [comment]
不使用char[][]数组，而是使用char*[]指针的形式，是可以使用sort和strcmp来排序的，如下
```cpp
// compare函数
bool compare(char* a, char* b)
{
    return strcmp(a, b) < 0;
}
// 数组定义
char *str[MAX_N] = {NULL}, pre = [MAX_L];
int n = 0;
// 输入
while (cin >> pre)
{
    str[n] = new char[MAX_L + MAX_L];
    strcpy(str[n++], pre);
}
// 排序
sort(str, str + n, compare);
```
